### ISSUE TITLE
Long term battery level graph

### ISSUE THREAD

**Issue by jklingen** [miska/HungerMeter#5]
I'd love to see a long term graph, displaying battery status over a longer timespan, e.g. one week or at least since last charge.
This would make it easy to discover facts like "after opening application x, there's constantly a higher decrease in battery level" or "while using application y for 30 minutes yesterday evening, the battery level dropped by 40%". 

I think this would make it easier for a lot of users to find out at the first sight where the battery lifetime goes and what they can do to extend it. (Being able to look at the current consumption is great, but does not help too much as long as you do not know a reference value).

By the way: thanks a lot for this great tool, great job :)

**Comment by miska** [comment]
Initial implementation partially done in 8e711b1831f1fab3b9a019a2f490237688611535, need to fix grid so the results could be somehow interpreted (hard to do currently), hopefully will be done soon.

**Comment by miska** [comment]
Done and released on openrepos, feel free to test and report bugs :-)
